Made a branch for testing IL2CPP support.  So far this message gets through in the Unity demo:
System.NotSupportedException: /Users/builduser/buildslave/unity/build/Tools/il2cpp/il2cpp/libil2cpp/icalls/mscorlib/System/AppDomain.cpp(99) : Unsupported internal call for IL2CPP:AppDomain::InternalGetContext - "This icall is only used in System.Threading.Thread.CurrentContext, which is used in the System.Runtime.Remoting namespace."
      at System.AppDomain.InternalGetContext () [0x00000] in <filename unknown>:0
      at System.Threading.Thread.get_CurrentContext () [0x00000] in <filename unknown>:0
      at System.Runtime.Remoting.Contexts.SynchronizationAttribute.EnterContext () [0x00000] in <filename unknown>:0
      at System.Threading.WaitHandle.WaitOne (TimeSpan timeout, Boolean exitContext) [0x00000] in <filename unknown>:0
      at Couchbase.Lite.Replicator.DefaultAuthHandler.ProcessResponse (System.Net.Http.HttpResponseMessage response, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
      at System.Net.Http.MessageProcessingHandler+<SendAsync>c__AnonStorey0+<SendAsync>c__AnonStorey1.<>m__0 () [0x00000] in <filename unknown>:0
      at System.Func`1[System.Net.Http.HttpResponseMessage].Invoke () [0x00000] in <filename unknown>:0
      at System.Threading.Tasks.TaskActionInvoker+FuncInvoke`1[System.Object].Invoke (System.Threading.Tasks.Task owner, System.Object state, System.Threading.Tasks.Task context) [0x00000] in <filename unknown>:0
      at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <filename unknown>:0
      at System.Threading.Tasks.Task.ThreadStart () [0x00000] in <filename unknown>:0
      at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0
      at System.Threading.Tasks.TpScheduler.TaskExecuterCallback (System.Object obj) [0x00000] in <filename unknown>:0